### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by ashgillman** [daviddoria/PatchMatch#1]
Hi David,

I was just wondering what license, if any, you had intended for this work (and included submodules) to be released under?

Many thanks,
Ashley Gillman

**Comment by daviddoria** [comment]
Hi Ashley,

I apologize for not including a license. A "please do whatever you want with it"-style license was the idea, so I suppose something like BSD or Apache? Do you have a specific use in mind?

Though before we worry about licenses, I'm not sure I ever really got this to work correctly? I'll put whatever license you want on it in exchange for a "fix all the broken stuff" pull request :)

David

**Comment by ashgillman** [comment]
I don't have any particular needs in a licence, I wasn't planning on using for any commercial purposes, for example (I'm a PhD student). I did get as far as compiling with GCC 6.4 before leaving work, happy to send the small changes upstream once I check it works :)

Out if curiosity, how much work do you think it would be to move the framework to 3D? I've noticed all the ImageType definitions are 2D, but wouldn't be too hard to change, but do you have any sence of whether far greater changes would be needed?

**Comment by daviddoria** [comment]
I think it should be setup fairly generically, so I wouldn't immediately exclude the potential for extension to 3D. However, I urge you not to get your hopes up until you work through the 2D version. Hopefully I was just doing something goofy, but as I mentioned I don't remember this actually producing any sane results.

**Comment by ashgillman** [comment]
Haha, no problems. I have a basic implementation but liked your architecture (although "Holy Gitmodules Batman!"). I will let you know if I get something working, thanks for sharing the code :)
